"""Data models for Forseti test scripts and results."""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class TestStatus(str, enum.Enum):
    """Status of a test execution."""

    PASS = "pass"
    FAIL = "fail"
    ERROR = "error"
    SKIP = "skip"


class TestPhase(str, enum.Enum):
    """Testing phase."""

    SIT = "SIT"
    UAT = "UAT"
    REGRESSION = "REGRESSION"


# ── Test Script Models (input) ──────────────────────────────────────


class TestStep(BaseModel):
    """A single test step described in natural language."""

    action: str = Field(description="Natural language action, e.g. 'กรอก username ว่า admin'")
    screenshot: bool = Field(default=True, description="Capture screenshot after this step")


class TestScenario(BaseModel):
    """A test scenario with steps and expected result."""

    name: str = Field(description="Scenario name, e.g. 'Successful Login'")
    steps: list[TestStep] = Field(description="Ordered list of test steps")
    expected: str = Field(description="Expected result in natural language")
    tags: list[str] = Field(default_factory=list, description="Tags for filtering")


class TestScript(BaseModel):
    """A complete test script loaded from YAML."""

    name: str = Field(description="Test suite name")
    base_url: str = Field(description="Base URL of the application under test")
    phase: TestPhase = Field(default=TestPhase.SIT, description="Testing phase (SIT/UAT)")
    scenarios: list[TestScenario] = Field(description="List of test scenarios")
    metadata: dict = Field(default_factory=dict, description="Additional metadata")


# ── LLM Action Models (LLM output) ─────────────────────────────────


class BrowserAction(BaseModel):
    """A structured browser action generated by LLM."""

    type: str = Field(description="Action type: navigate, click, type, select, wait, screenshot")
    selector: Optional[str] = Field(default=None, description="CSS/text selector for the element")
    value: Optional[str] = Field(default=None, description="Value to type or URL to navigate to")
    description: str = Field(default="", description="Human-readable description of this action")


class ActionPlan(BaseModel):
    """Plan of browser actions generated by LLM for a test step."""

    step_description: str = Field(description="Original natural language step")
    actions: list[BrowserAction] = Field(description="Ordered browser actions to execute")


# ── Test Result Models (output) ─────────────────────────────────────


class StepResult(BaseModel):
    """Result of executing a single test step."""

    step: TestStep
    status: TestStatus = TestStatus.PASS
    actions_executed: list[BrowserAction] = Field(default_factory=list)
    screenshot_path: Optional[str] = None
    error_message: Optional[str] = None
    duration_ms: int = 0


class ScenarioResult(BaseModel):
    """Result of executing a complete test scenario."""

    scenario: TestScenario
    status: TestStatus = TestStatus.PASS
    step_results: list[StepResult] = Field(default_factory=list)
    assertion_result: Optional[str] = None
    error_message: Optional[str] = None
    duration_ms: int = 0
    started_at: datetime = Field(default_factory=datetime.now)
    finished_at: Optional[datetime] = None


class TestSuiteResult(BaseModel):
    """Result of executing a complete test suite."""

    script: TestScript
    scenario_results: list[ScenarioResult] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=datetime.now)
    finished_at: Optional[datetime] = None

    @property
    def total(self) -> int:
        return len(self.scenario_results)

    @property
    def passed(self) -> int:
        return sum(1 for r in self.scenario_results if r.status == TestStatus.PASS)

    @property
    def failed(self) -> int:
        return sum(1 for r in self.scenario_results if r.status == TestStatus.FAIL)

    @property
    def errors(self) -> int:
        return sum(1 for r in self.scenario_results if r.status == TestStatus.ERROR)

    @property
    def skipped(self) -> int:
        return sum(1 for r in self.scenario_results if r.status == TestStatus.SKIP)

    @property
    def pass_rate(self) -> float:
        """Pass rate as percentage (0-100)."""
        return (self.passed / self.total * 100) if self.total > 0 else 0.0

    @property
    def duration_ms(self) -> int:
        return sum(r.duration_ms for r in self.scenario_results)
