"""Executor: translates LLM action plans into Playwright browser commands."""

from __future__ import annotations

import asyncio
import logging
import time
from pathlib import Path

from playwright.async_api import Page

from forseti.models import ActionPlan, BrowserAction, StepResult, TestStatus, TestStep

logger = logging.getLogger("forseti.agent.executor")


class ActionExecutor:
    """Executes browser actions generated by LLM on a Playwright page."""

    def __init__(self, page: Page, screenshots_dir: Path, timeout_ms: int = 30000):
        self.page = page
        self.screenshots_dir = screenshots_dir
        self.timeout_ms = timeout_ms
        self.screenshots_dir.mkdir(parents=True, exist_ok=True)

    async def execute_plan(
        self, plan: ActionPlan, step: TestStep, scenario_name: str, step_index: int
    ) -> StepResult:
        """Execute all actions in a plan and return the step result."""
        start = time.monotonic()
        result = StepResult(step=step)
        actions_executed = []

        try:
            for i, action in enumerate(plan.actions):
                logger.info(f"  Action {i + 1}/{len(plan.actions)}: {action.type} — {action.description}")
                await self._execute_action(action)
                actions_executed.append(action)

            # Take screenshot after step if requested
            if step.screenshot:
                ss_name = f"{scenario_name}__step{step_index + 1}.png".replace(" ", "_")
                ss_path = self.screenshots_dir / ss_name
                await self.page.screenshot(path=str(ss_path))
                result.screenshot_path = str(ss_path)

            result.status = TestStatus.PASS

        except Exception as e:
            logger.error(f"  ❌ Action failed: {e}")
            result.status = TestStatus.ERROR
            result.error_message = str(e)

            # Take error screenshot
            ss_name = f"{scenario_name}__step{step_index + 1}__ERROR.png".replace(" ", "_")
            ss_path = self.screenshots_dir / ss_name
            try:
                await self.page.screenshot(path=str(ss_path))
                result.screenshot_path = str(ss_path)
            except Exception:
                pass

        result.actions_executed = actions_executed
        result.duration_ms = int((time.monotonic() - start) * 1000)
        return result

    async def _execute_action(self, action: BrowserAction) -> None:
        """Execute a single browser action."""
        match action.type:
            case "navigate":
                url = action.value or ""
                if not url.startswith("http"):
                    # Relative URL — resolve against current page
                    url = self.page.url.rstrip("/") + "/" + url.lstrip("/")
                await self.page.goto(url, wait_until="domcontentloaded", timeout=self.timeout_ms)

            case "click":
                locator = self._resolve_locator(action.selector)
                await locator.click(timeout=self.timeout_ms)

            case "type":
                locator = self._resolve_locator(action.selector)
                await locator.fill(action.value or "", timeout=self.timeout_ms)

            case "select":
                locator = self._resolve_locator(action.selector)
                await locator.select_option(action.value or "", timeout=self.timeout_ms)

            case "wait":
                if action.selector:
                    await self.page.wait_for_selector(action.selector, timeout=self.timeout_ms)
                elif action.value:
                    await asyncio.sleep(int(action.value) / 1000)
                else:
                    await asyncio.sleep(1)

            case "screenshot":
                name = action.value or "manual_screenshot.png"
                path = self.screenshots_dir / name
                await self.page.screenshot(path=str(path))

            case "assert_text":
                text = action.value or ""
                locator = self.page.get_by_text(text)
                await locator.wait_for(timeout=self.timeout_ms)

            case "assert_element":
                await self.page.wait_for_selector(
                    action.selector or "", timeout=self.timeout_ms
                )

            case "scroll":
                direction = (action.value or "down").lower()
                if direction == "down":
                    await self.page.evaluate("window.scrollBy(0, 500)")
                elif direction == "up":
                    await self.page.evaluate("window.scrollBy(0, -500)")
                else:
                    try:
                        pixels = int(direction)
                        await self.page.evaluate(f"window.scrollBy(0, {pixels})")
                    except ValueError:
                        await self.page.evaluate("window.scrollBy(0, 500)")

            case "hover":
                locator = self._resolve_locator(action.selector)
                await locator.hover(timeout=self.timeout_ms)

            case _:
                logger.warning(f"Unknown action type: {action.type}")

    def _resolve_locator(self, selector: str | None):
        """Resolve a selector string into a Playwright locator.

        Supports multiple comma-separated selectors (tries each until one works).
        """
        if not selector:
            raise ValueError("No selector provided for action")

        # Split comma-separated selectors and try each
        selectors = [s.strip() for s in selector.split(",") if s.strip()]

        if len(selectors) == 1:
            return self._single_locator(selectors[0])

        # For multiple selectors, use first-match approach
        return self._single_locator(selectors[0]).or_(
            *[self._single_locator(s) for s in selectors[1:]]
        )

    def _single_locator(self, selector: str):
        """Create a locator from a single selector string."""
        # Playwright-specific pseudo-selectors
        if ":has-text(" in selector:
            return self.page.locator(selector)
        if selector.startswith("text=") or selector.startswith('"'):
            return self.page.locator(selector)

        # Standard CSS selector
        return self.page.locator(selector)
