"""GitHub issue integration for test failures."""

from __future__ import annotations

import logging

from forseti.config import GitHubConfig
from forseti.models import ScenarioResult, TestStatus, TestSuiteResult

logger = logging.getLogger("forseti.reporter.github_issue")


class GitHubIssueReporter:
    """Creates GitHub issues for failed test scenarios."""

    def __init__(self, config: GitHubConfig):
        self.config = config
        self._repo = None

    def _get_repo(self):
        """Lazy-load GitHub repo connection."""
        if self._repo is None:
            from github import Github

            gh = Github(self.config.token)
            self._repo = gh.get_repo(self.config.repo)
        return self._repo

    def report_failures(self, result: TestSuiteResult) -> list[str]:
        """Create GitHub issues for all failed scenarios.

        Args:
            result: Test suite result containing scenario results.

        Returns:
            List of created issue URLs.
        """
        if not self.config.enabled:
            logger.info("GitHub integration disabled, skipping issue creation")
            return []

        if not self.config.token or not self.config.repo:
            logger.warning("GitHub token or repo not configured")
            return []

        failed = [
            sr for sr in result.scenario_results if sr.status in (TestStatus.FAIL, TestStatus.ERROR)
        ]

        if not failed:
            logger.info("✅ No failures — no GitHub issues to create")
            return []

        issue_urls = []
        for sr in failed:
            try:
                url = self._create_issue(sr, result)
                issue_urls.append(url)
                logger.info(f"🐙 GitHub issue created: {url}")
            except Exception as e:
                logger.error(f"Failed to create GitHub issue for '{sr.scenario.name}': {e}")

        return issue_urls

    def _create_issue(self, scenario_result: ScenarioResult, suite_result: TestSuiteResult) -> str:
        """Create a single GitHub issue for a failed scenario."""
        repo = self._get_repo()

        title = (
            f"⚖️ [Forseti] Test Failed: {scenario_result.scenario.name} "
            f"({suite_result.script.phase.value})"
        )

        # Build issue body
        body_parts = [
            "## ⚖️ Forseti E2E Test Failure Report\n",
            f"**Test Suite:** {suite_result.script.name}",
            f"**Phase:** {suite_result.script.phase.value}",
            f"**Target URL:** {suite_result.script.base_url}",
            f"**Scenario:** {scenario_result.scenario.name}",
            f"**Status:** `{scenario_result.status.value}`",
            f"**Timestamp:** {scenario_result.started_at}",
            "",
            "### 📝 Test Steps",
            "",
        ]

        for i, step_r in enumerate(scenario_result.step_results):
            icon = "✅" if step_r.status == TestStatus.PASS else "❌"
            body_parts.append(f"{i + 1}. {icon} {step_r.step.action} ({step_r.duration_ms}ms)")
            if step_r.error_message:
                body_parts.append(f"   > ⚠️ Error: {step_r.error_message}")

        body_parts.extend([
            "",
            "### 🎯 Expected Result",
            f"> {scenario_result.scenario.expected}",
            "",
        ])

        if scenario_result.assertion_result:
            body_parts.extend([
                "### 🔍 Assertion Result",
                f"> {scenario_result.assertion_result}",
                "",
            ])

        if scenario_result.error_message:
            body_parts.extend([
                "### ❌ Error",
                f"```\n{scenario_result.error_message}\n```",
                "",
            ])

        body_parts.extend([
            "---",
            "*Generated by ⚖️ Forseti v0.1.0*",
        ])

        body = "\n".join(body_parts)

        issue = repo.create_issue(
            title=title,
            body=body,
            labels=self.config.labels,
            assignees=self.config.assignees if self.config.assignees else [],
        )

        return issue.html_url
