"""ISO 29110 Report Generator — Sprint 02.

Generates SI-04 format markdown test reports from TestSuiteResult.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from forseti.models import TestSuiteResult, TestStatus


class ISOReportGenerator:
    """Generate ISO 29110 SI-04 compliant test reports."""

    def generate(self, result: TestSuiteResult) -> str:
        """Generate SI-04 markdown from TestSuiteResult.

        Returns:
            Markdown string.
        """
        lines = []

        # Header
        lines.append(f"# SI-04 — E2E Test Report: {result.script.name}")
        lines.append("")
        lines.append("| รายการ | รายละเอียด |")
        lines.append("|---|---|")
        lines.append(f"| **เอกสาร** | SI-04 (Auto-generated) |")
        lines.append(f"| **Test Suite** | {result.script.name} |")
        lines.append(f"| **Phase** | {result.script.phase.value} |")
        lines.append(f"| **Base URL** | {result.script.base_url} |")
        lines.append(f"| **Started** | {result.started_at} |")
        lines.append(f"| **Finished** | {result.finished_at} |")
        lines.append(f"| **Duration** | {result.duration_ms}ms |")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| Total | {result.total} |")
        lines.append(f"| ✅ Passed | {result.passed} |")
        lines.append(f"| ❌ Failed | {result.failed} |")
        lines.append(f"| ⚠️ Error | {result.errors} |")
        lines.append(f"| ⏭️ Skipped | {result.skipped} |")
        lines.append(f"| **Pass Rate** | **{result.pass_rate:.1f}%** |")
        lines.append("")

        # Test Matrix
        lines.append("## Test Results")
        lines.append("")
        lines.append("| # | Scenario | Status | Duration | Error |")
        lines.append("|---|---|---|---|---|")

        for i, sr in enumerate(result.scenario_results):
            icon = {
                TestStatus.PASS: "✅",
                TestStatus.FAIL: "❌",
                TestStatus.ERROR: "⚠️",
                TestStatus.SKIP: "⏭️",
            }.get(sr.status, "❓")
            error = sr.error_message or "—"
            lines.append(
                f"| {i+1} | {sr.scenario.name} | {icon} {sr.status.value} "
                f"| {sr.duration_ms}ms | {error} |"
            )

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(f"*Generated by Forseti ⚖️ at {datetime.now().isoformat()}*")
        lines.append("")

        return "\n".join(lines)

    def save(
        self,
        result: TestSuiteResult,
        output_dir: str = "reports",
        filename: str | None = None,
    ) -> Path:
        """Generate and save ISO report to file.

        Returns:
            Path to saved file.
        """
        md = self.generate(result)

        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        if not filename:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"SI-04_{result.script.phase.value}_{ts}.md"

        path = out / filename
        path.write_text(md, encoding="utf-8")
        return path
